-- Customer Shopping Behavior Analysis

--Q1. What is the total revenue generated by male vs. female customers?

SELECT
   gender,
   SUM(purchase_amount) AS revenue
FROM
   customer_shopping
GROUP BY
   gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT
   customer_id,
   purchase_amount
FROM
   customer_shopping
WHERE
   discount_applied = 'Yes'
   AND purchase_amount > (
      SELECT
         round(AVG(purchase_amount), 2)
      FROM
         customer_shopping
   );

--Q3. Which are the top 5 products with the highest average review rating?

SELECT
   *
FROM
   (
      SELECT
         item_purchased,
         AVG(review_rating) AS avg_rating
      FROM
         customer_shopping
      GROUP BY
         item_purchased
      ORDER BY
         avg_rating DESC
   )
WHERE
   ROWNUM <= 5;

-- or 

SELECT
   *
FROM
   (
      SELECT
         item_purchased,
         round(AVG(review_rating), 1) AS avg_rating,
         DENSE_RANK() OVER(
            ORDER BY
               AVG(review_rating) DESC
         ) AS rating_rank
      FROM
         customer_shopping
      GROUP BY
         item_purchased
   )
WHERE
   rating_rank <= 5;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT
   shipping_type,
   round(AVG(purchase_amount), 2) AS avg_amount
FROM
   customer_shopping
WHERE
   shipping_type IN (
      'Standard',
      'Express'
   )
GROUP BY
   shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

SELECT
   subscription_status,
   COUNT(customer_id),
   round(AVG(purchase_amount), 2) AS avg_spend,
   SUM(purchase_amount) AS total_revenue
FROM
   customer_shopping
WHERE
   subscription_status IN (
      'Yes',
      'No'
   )
GROUP BY
   subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT
   *
FROM
   (
      SELECT
         item_purchased,
         round(100 * SUM(
            CASE
               WHEN discount_applied = 'Yes' THEN
                  1
               ELSE
                  0
            END
         ) / COUNT(*), 2) AS discount_rate
      FROM
         customer_shopping
      GROUP BY
         item_purchased
      ORDER BY
         discount_rate DESC
   )
WHERE
   ROWNUM <= 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

WITH customer_type AS (
   SELECT
      customer_id,
      previous_purchases,
      CASE
         WHEN previous_purchases = 1            THEN
            'New'
         WHEN previous_purchases BETWEEN 2 AND 10 THEN
            'Returning'
         ELSE
            'Loyal'
      END AS customer_segment
   FROM
      customer_shopping
)
SELECT
   customer_segment,
   COUNT(*) AS "Number of Customers"
FROM
   customer_type
GROUP BY
   customer_segment;



--Q8. What are the top 3 most purchased products within each category? 

SELECT
   category,
   item_purchased,
   total_purchases,
   item_rank
FROM
   (
      SELECT
         category,
         item_purchased,
         COUNT(*) AS total_purchases,
         ROW_NUMBER() OVER(
            PARTITION BY category
            ORDER BY
               COUNT(*) DESC
         ) AS item_rank
      FROM
         customer_shopping
      GROUP BY
         category,
         item_purchased
   )
WHERE
   item_rank <= 3
ORDER BY
   category,
   total_purchases DESC;

-- With CTE 

WITH item_count AS (
   SELECT
      category,
      item_purchased,
      COUNT(*) AS total_purchases,
      ROW_NUMBER() OVER(
         PARTITION BY category
         ORDER BY
            COUNT(*) DESC
      ) AS item_rank
   FROM
      customer_shopping
   GROUP BY
      category,
      item_purchased
)
SELECT
   category,
   item_purchased,
   total_purchases,
   item_rank
FROM
   item_count
WHERE
   item_rank <= 3;


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT
   subscription_status,
   COUNT(*) AS repeat_buyers
FROM
   customer_shopping
WHERE
   previous_purchases >= 5
GROUP BY
   subscription_status;


--Q10. What is the revenue contribution of each age group? 

SELECT
   age_group,
   SUM(purchase_amount) AS revenue_contribution
FROM
   customer_shopping
GROUP BY
   age_group
ORDER BY
   revenue_contribution DESC;

